version: '3.8'

services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://root:password123@mongo:27017/passport_buddy?authSource=admin
      JWT_SECRET: local-dev-secret-key-change-in-production
      EMAIL_PROVIDER: resend
      RESEND_API_KEY: ${RESEND_API_KEY:-dummy-key}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      VITE_API_URL: http://localhost:3000
      VITE_GRAPHQL_URL: http://localhost:3000/graphql
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

volumes:
  mongo_data: