name: passport_buddy
description: "Connect with fellow travelers and share your adventures"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  # This is the standard SDK constraint format. Your previous one was slightly off.
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Networking & State
  graphql_flutter: ^5.2.0
  flutter_dotenv: ^5.1.0
  dio: ^5.3.3
  http: ^1.1.0
  http_parser: ^4.0.2

  # Utility
  intl: ^0.20.2
  
  # Media
  image_picker: ^1.0.4
  share_plus: ^10.1.3
  
  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  
  # State Management
  provider: ^6.1.1
  
  # Logging
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  mockito: ^5.4.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets section
  assets:
    - .env
    - assets/data/airports.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
